---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-latest
    container_name: qbittorrent
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /mnt/hdd/media:/mnt/hdd/media
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

networks:
  caddy:
    external: true
