*.ade
*.adp
*.apk
*.app
*.arj
*.bas
*.bat
*.bin
*.chm
*.cmd
*.com
*.cpl
*.crt
*.dll
*.drv
*.exe
*.hlp
*.hta
*.html
*.inf
*.ins
*.ipa
*.iso
*.isp
*.jar
*.js
*.jse
*.key
*.lnk
*.mda
*.mdb
*.mdt
*.mdw
*.mdz
*.mht
*.mhtml
*.msi
*.msp
*.nsh
*.ocx
*.php
*.pif
*.potm
*.potx
*.ppam
*.ppsx
*.pptm
*.ps1
*.ps2
*.psd1
*.psm1
*.py
*.reg
*.scf
*.scr
*.sh
*.sldm
*.sldx
*.sys
*.tmp
*.torrent
*.vb
*.vbe
*.vbs
*.vxd
*.wsf
*.wsh
*.xlam
*.xlsb
*.xlsm
*.xltm
*.zipx
*sample.avi
*sample.mkv
*sample.mp4
*.zip
*.rar
*.7z
*.gz
*.tar
