services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs:ro
      - ./sites:/srv/sites:ro
      - data:/data
      - config:/config
    networks:
      - caddy
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      VAULT_DOMAIN: ${VAULT_DOMAIN}
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
  config:

networks:
  caddy:
    name: caddy
