services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - data:/data
      - config:/config
    networks:
      - caddy
    environment:
      VAULT_DOMAIN: ${VAULT_DOMAIN}

volumes:
  data:
  config:

networks:
  caddy:
    external: true
