services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${PLEX_CONFIG}:/config
      - ${PLEX_TV}:/tv
      - ${PLEX_ANIME_SERIES}:/anime_series
      - ${PLEX_ANIME_MOVIES}:/anime_movies
      - ${PLEX_MOVIES}:/movies
      - ${PLEX_ONE_PIECE}:/one_piece
    restart: unless-stopped
