services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - SIGNUPS_ALLOWED=false
    volumes:
      - ./vw-data:/data
    networks:
      - caddy

networks:
  caddy:
    external: true
