services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${UID}:${GID}
    network_mode: host
    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${JELLYFIN_CACHE}:/cache
      - ${JELLYFIN_TV}:/tv
      - ${JELLYFIN_ANIME_SERIES}:/anime_series
      - ${JELLYFIN_ANIME_MOVIES}:/anime_movies
      - ${JELLYFIN_MOVIES}:/movies
      - ${JELLYFIN_ONE_PIECE}:/one_piece
      # Optional fonts support (subtitle burn-in, transcoding)
      # - ${JELLYFIN_FONTS}:/usr/local/share/fonts/custom:ro
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_URL}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
